language: c

sudo: false

os:
  - linux
  - osx

env:
  global:
    - SETUP_XVFB=True
    - CONDA_DEPENDENCIES='pytest'
  matrix:
    - env: PYTHON_VERSION=2.7 USE_QT_API=PyQt5
    - env: PYTHON_VERSION=2.7 USE_QT_API=PyQt4
    - env: PYTHON_VERSION=2.7 USE_QT_API=PySide
    - env: PYTHON_VERSION=3.4 USE_QT_API=PyQt4
    - env: PYTHON_VERSION=3.5 USE_QT_API=PyQt4
    - env: PYTHON_VERSION=3.5 USE_QT_API=PyQt5

before_install:
  # Test environments for different Qt bindings
  - if [[ "$USE_QT_API" == "PyQt5" ]]; then
      export CONDA_DEPENDENCIES='qt5 pyqt5'$CONDA_DEPENDENCIES;
      export CONDA_CHANNELS='spyder-ide';
    elif [[ "$USE_QT_API" == "PyQt4" ]]; then
      export CONDA_DEPENDENCIES='qt pyqt'$CONDA_DEPENDENCIES;
    elif [[ "$USE_QT_API" == "PySide" ]]; then
      export CONDA_DEPENDENCIES='qt pyside'$CONDA_DEPENDENCIES;
    fi

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - python setup.py install

before_script:
  - cd tests

script:
  - py.test
