# Travis CI(http://travis-ci.org) configuration file
language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2" Sphinx depends on Pygments, which only supports Python 3.3+
  - "3.3"
  - "3.4"

before_install:
  # Update APT cache data since it may outdated
  - sudo apt-get -qq update
  # according to Debian control file from Ubuntu 12.04
  - sudo apt-get install -y git rsync gettext

# command to install dependencies, git and python are pre-installed in build box thus are ignored
install:
  - pip install sphinx
  # SIP
  - wget "http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz"
  - tar xzf sip-4.16.5.tar.gz
  - cd sip-4.16.5
  - python configure.py
  - make -j4
  - sudo make install
  - cd ..
  # PyQt4
  - wget "http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz"
  - tar xzf PyQt-x11-gpl-4.11.3.tar.gz
  - cd PyQt-x11-gpl-4.11.3
  - python configure.py --confirm-license
  - make -j4
  - make install
  - cd ..
  # Additional dependency for python 2.6
  - pip install argparse
  # Pylint
  - pip install astroid==1.3.8
  - pip install pylint==1.4.4

script:
  - make all
  - make doc
  # Git test setup
  - git config --global user.name "Git Cola"
  - git config --global user.email git-cola@localhost.localdomain
  # TODO tests currently fail on Python3 due to sip
  - env GIT_COLA_NO_SIP_SETAPI=1 GIT_COLA_NO_HISTORY=1 make test flags=--verbose
  # pylint 1.4 uses python2.7+ syntax so skip pylint on python2.6
  - test "2.6" = "$TRAVIS_PYTHON_VERSION" || make pylint
